pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndPackage
  jobs: 
  - job: Package
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '22.x'
    - task: Npm@1
      inputs:
        command: 'install'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run package'