name: CI_Integration_Windows

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

    - name: Configuring Git LF Settings
      run: |
        git config --global core.autocrlf false

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build and Test
      run: |
        npm install
        npm run build-and-lint
        npm run test

    - name: Creating .vsix
      run: |
        npm run package
